### ISSUE TITLE
Linker errors on Carthage update

### ISSUE THREAD

**Issue by BryanJBryce** [Ben-G/Meet#2]
The following build commands failed:
    Ld ~/Library/Developer/Xcode/DerivedData/Nimble-eonjtnkeqbjxzecwwoephxsenenu/Build/Products/Release-appletvos/Nimble.framework/Nimble normal arm64
(1 failure)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    Ld ~/Library/Developer/Xcode/DerivedData/Nimble-eonjtnkeqbjxzecwwoephxsenenu/Build/Products/Release-appletvos/Nimble.framework/Nimble normal arm64
(1 failure)

**Comment by agentk** [comment]
That sounds related to the same issue we had in ReSwift: http://reswift.github.io/ReSwift/master/testing.html

I'm not familiar enough with CocoaPods to suggest a workaround yet.

**Comment by dimazen** [comment]
I'm having the same issue.

**Comment by Ben-G** [comment]
@BryanJBryce @dimazen I've updated the install instructions, you should be able to get dependencies installed by running

```
carthage update --no-use-binaries --platform iOS
```

I also have specified the exact version of `ReSwift` this project uses in the Cartfile, you should update your git repo if you have a local copy.

Let me know if this fixes your issues!
