### ISSUE TITLE
How you stop the location service from dispatching the location action?

### ISSUE THREAD

**Issue by mortyccp** [Ben-G/Meet#3]
I see you are using `ActionCreator` to keep dispatching location action to the store, but how you stop this dispatching when you don't need the location service anymore?

**Comment by Ben-G** [comment]
(Sorry for super late response, currently browsing open issues)

Stopping the location service from dispatching actions would work the same way as if you weren't using ReSwift. You'd need to create a mechanism to stop location updates. Either a direct reference to the location service, or an action that results in stopping the location service.

Hope this makes sense!
